# Generated by Django 5.1.4 on 2024-12-17 17:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camisa', models.TextField(max_length=100, unique=True)),
                ('estoque', models.IntegerField()),
                ('custo', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('tamanho', models.TextField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=100)),
                ('quantidade', models.IntegerField(default=None)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='keniscompany.produtos', to_field='camisa')),
            ],
        ),
    ]
